# Generated by Django 6.0.4 on 2026-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='minutes_retard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presence',
            name='retenue_salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
