# Generated by Django 6.0.6 on 2026-07-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_employe_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='photo_profil',
        ),
        migrations.AddField(
            model_name='employe',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employe.departement'),
        ),
    ]
