# Generated by Django 6.0.6 on 2026-07-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_remove_departement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='date_embauche',
        ),
    ]
