# Generated by Django 6.0.4 on 2026-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_remove_employe_date_embauche'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=12),
        ),
    ]
